baseurl: https://alanneyton.github.io/
# publishdir: /servers/bitbucket/alexgorovitz.bitbucket.io/
publishdir: /servers/localhost/projects/athletway/trust-linkprofile/sites/alanneyton.github.io/
metaDataFormat: yaml
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: trac
pygmentsUseClasses: true
theme: beautifulhugo
title: Alan Neyton
uglyurls: false
DefaultContentLanguage: en
languageCode: en-US
Params:
  comments: false
  commit: false
  dateFormat: January 2, 2006
  # favicon: img/favicon.ico
  # logo: img/avatar-icon.png
  readingTime: true
  # rss: true
  # subtitle: DEMO SLOGAN
  useHLJS: true
permalinks:
  post: /:year/:month/:slug/
  category: /categories/:slug/
Author:
  # bandcamp: username
  # email: youremail@domain.com
  # facebook: username
  # github: username
  # gitlab: username
  # googleplus: +username
  # instagram: username
  # itchio: username
  # linkedin: username
  # name: Some Person
  # paypal: username
  # reddit: username
  # snapchat: username
  # soundcloud: username
  # spotify: username
  # stackoverflow: users/XXXXXXX/username
  # telegram: username
  # twitter: username
  # vk: username
  # website: yourwebsite.com
  # xing: username
  # youtube: user/username
menu:
  main:
  - name: Blog
    url: "/"
    weight: 1
  - name: Tags
    url: "/tags/"
    weight: 2
    #   - identifier: categories
    #   name: Categories
    #   weight: 3
    #   - name: Anabolics
    #    parent: categories
    #    url: /anabolics/
    #    weight: 1
    #   - name: Math Sample
    #   parent: samples
    #   url: post/2017-03-05-math-sample
    #   weight: 2
    #   - name: Code Sample
    #   parent: samples
    #   url: post/2016-03-08-code-sample
    #   weight: 3
